# Site settings
title: 3DPrintScanner
email: 3DPrintScanner@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Description of skills, projects and relevant work from 3DPrintscanner
baseurl: "" # the subpath of your site, e.g. /blog/
url: "localhost:4000" # the base hostname & protocol for your site
twitter_username: 3DPrintScanner
github_username:  3DPrintScanner

# Build settings
markdown: kramdown
